#!/usr/bin/env bash
# Load personal standard shell library
# shellcheck source=/dev/null
if [[ -r ~/etc/lib.bash ]]; then . ~/etc/lib.bash; else echo "FATAL ERROR: ~/etc/lib.bash not found." ; exit 1 ; fi
need_progs brew

shopt -s lastpipe

repo=$(brew --repo homebrew/core)
build_dir=~/Library/Caches/build-core-mojave
url=https://github.com/gromgit/homebrew-core-mojave

anti_depends=(
  ":linux"
  "macos: :catalina"
)

cd "$repo" || fatal "Can't cd into $repo"

if [[ $# -eq 0 ]]; then
  # Automatically select all non-bottled formulae
  work=()
  grep -L "bottle do" Formula/*.rb | while read -r i; do
    # Now drop everything that can't be built
    for drop in "${anti_depends[@]}"; do
      if grep -q "depends_on $drop" "$i"; then
        info "Ignoring $(basename "$i" .rn) because $drop"
        continue 2
      fi
    done
    work+=("$(basename "$i" .rb)")
  done
  set -- "${work[@]}"
fi

# Sort by dependency tree
# shellcheck disable=SC2046
set -- $(brew deps -n --include-build --include-test --union "$@") "$@"

for f in "$@"; do
  formula=Formula/${f}.rb
  installed=""
  [[ -d ${HOMEBREW_CELLAR}/${f} ]] && installed=yes
  if grep -q 'depends_on :linux' "$formula"; then
    warn "Skipping $f - Linux-only"
    continue
  fi
  grep 'disable!' "$formula" | while read -r _ f1 f2 _; do
    if [[ $f1 == "date:" && ! $f2 > $(date +%Y-%m-d) ]]; then
      warn "Skipping $f - disabled"
      continue
    fi
  done
  if ! grep -q "bottle do" "Formula/${f}.rb"; then
    (
      mkdir -p "$build_dir/$f"
      cd "$build_dir/$f" || fatal "Can't cd into $(dirname "$0")"
      cmd brew test-bot --only-formulae --publish --root-url="${url}/releases/download/${f}" "$f"
    )
    cmd brew upload-mojave &&
    rm -f "${HOMEBREW_CELLAR}"/*.tar &&
    cmd git push
  fi
  # Clean up manually afterwards
  if [[ -z $installed && -d $HOMEBREW_CELLAR/$f ]]; then
    cmd brew rm "$f" && cmd brew autoremove
  fi
done
