#!/usr/bin/env bash
# Load personal standard shell library
# shellcheck source=/dev/null
if [[ -r ~/etc/lib.bash ]]; then . ~/etc/lib.bash; else echo "FATAL ERROR: ~/etc/lib.bash not found." ; exit 1 ; fi
need_progs brew diff

cd "$(dirname "$(brew --repo homebrew/core)")" || fatal "Can't cd to homebrew tap dir"
for f in "$@"; do
  diff -u homebrew-{real,}core/Formula/"$f".rb
done
